version: '3.9'

services:
  estoque-app:
    build: .
    container_name: estoque_flask
    ports:
      - "8080:5000"   # roda no host 8080, dentro do container 5000
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: estoque_postgres
    restart: always
    environment:
      POSTGRES_USER: estoque_user
      POSTGRES_PASSWORD: estoque_pass
      POSTGRES_DB: estoque_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: 
